using ProudNet.Serialization;

namespace Netsphere.Network.Message.GameRule
{
    public interface IGameRuleMessage
    { }

    public class GameRuleMessageFactory : MessageFactory<GameRuleOpCode, IGameRuleMessage>
    {
        public GameRuleMessageFactory()
        {
            // S2C
            Register<SEnterPlayerAckMessage>(GameRuleOpCode.SEnterPlayerAck);
            Register<SLeavePlayerAckMessage>(GameRuleOpCode.SLeavePlayerAck);
            Register<SLeavePlayerRequestAckMessage>(GameRuleOpCode.SLeavePlayerRequestAck);
            Register<SChangeTeamAckMessage>(GameRuleOpCode.SChangeTeamAck);
            Register<SChangeTeamFailAckMessage>(GameRuleOpCode.SChangeTeamFailAck);
            Register<SMixChangeTeamAckMessage>(GameRuleOpCode.SMixChangeTeamAck);
            Register<SMixChangeTeamFailAckMessage>(GameRuleOpCode.SMixChangeTeamFailAck);
            Register<SAutoAssignTeamAckMessage>(GameRuleOpCode.SAutoAssignTeamAck);
            Register<SEventMessageAckMessage>(GameRuleOpCode.SEventMessageAck);
            Register<SBriefingAckMessage>(GameRuleOpCode.SBriefingAck);
            Register<SChangeStateAckMessage>(GameRuleOpCode.SChangeStateAck);
            Register<SChangeSubStateAckMessage>(GameRuleOpCode.SChangeSubStateAck);
            Register<SDestroyGameRuleAckMessage>(GameRuleOpCode.SDestroyGameRuleAck);
            Register<SChangeMasterAckMessage>(GameRuleOpCode.SChangeMasterAck);
            Register<SChangeRefeReeAckMessage>(GameRuleOpCode.SChangeRefeReeAck);
            Register<SChangeTheFirstAckMessage>(GameRuleOpCode.SChangeTheFirstAck);
            Register<SChangeSlaughtererAckMessage>(GameRuleOpCode.SChangeSlaughtererAck);
            Register<SReadyRoundAckMessage>(GameRuleOpCode.SReadyRoundAck);
            Register<SBeginRoundAckMessage>(GameRuleOpCode.SBeginRoundAck);
            Register<SAvatarChangeAckMessage>(GameRuleOpCode.SAvatarChangeAck);
            Register<SChangeRuleNotifyAckMessage>(GameRuleOpCode.SChangeRuleNotifyAck);
            Register<SChangeRuleAckMessage>(GameRuleOpCode.SChangeRuleAck);
            Register<SChangeRuleResultMsgAckMessage>(GameRuleOpCode.SChangeRuleResultMsgAck);
            Register<SMissionNotifyAckMessage>(GameRuleOpCode.SMissionNotifyAck);
            Register<SMissionScoreAckMessage>(GameRuleOpCode.SMissionScoreAck);
            Register<SScoreKillAckMessage>(GameRuleOpCode.SScoreKillAck);
            Register<SScoreKillAssistAckMessage>(GameRuleOpCode.SScoreKillAssistAck);
            Register<SScoreOffenseAckMessage>(GameRuleOpCode.SScoreOffenseAck);
            Register<SScoreOffenseAssistAckMessage>(GameRuleOpCode.SScoreOffenseAssistAck);
            Register<SScoreDefenseAckMessage>(GameRuleOpCode.SScoreDefenseAck);
            Register<SScoreDefenseAssistAckMessage>(GameRuleOpCode.SScoreDefenseAssistAck);
            Register<SScoreHealAssistAckMessage>(GameRuleOpCode.SScoreHealAssistAck);
            Register<SScoreGoalAckMessage>(GameRuleOpCode.SScoreGoalAck);
            Register<SScoreGoalAssistAckMessage>(GameRuleOpCode.SScoreGoalAssistAck);
            Register<SScoreReboundAckMessage>(GameRuleOpCode.SScoreReboundAck);
            Register<SScoreSuicideAckMessage>(GameRuleOpCode.SScoreSuicideAck);
            Register<SScoreTeamKillAckMessage>(GameRuleOpCode.SScoreTeamKillAck);
            Register<SScoreRoundWinAckMessage>(GameRuleOpCode.SScoreRoundWinAck);
            Register<SScoreSLRoundWinAckMessage>(GameRuleOpCode.SScoreSLRoundWinAck);
            Register<SItemsChangeAckMessage>(GameRuleOpCode.SItemsChangeAck);
            Register<SPlayerGameModeChangeAckMessage>(GameRuleOpCode.SPlayerGameModeChangeAck);
            Register<SRefreshGameRuleInfoAckMessage>(GameRuleOpCode.SRefreshGameRuleInfoAck);
            Register<SArcadeScoreSyncAckMessage>(GameRuleOpCode.SArcadeScoreSyncAck);
            Register<SArcadeBeginRoundAckMessage>(GameRuleOpCode.SArcadeBeginRoundAck);
            Register<SArcadeStageBriefingAckMessage>(GameRuleOpCode.SArcadeStageBriefingAck);
            Register<SArcadeEnablePlayeTimeAckMessage>(GameRuleOpCode.SArcadeEnablePlayeTimeAck);
            Register<SArcadeStageInfoAckMessage>(GameRuleOpCode.SArcadeStageInfoAck);
            Register<SArcadeRespawnAckMessage>(GameRuleOpCode.SArcadeRespawnAck);
            Register<SArcadeDeathPlayerInfoAckMessage>(GameRuleOpCode.SArcadeDeathPlayerInfoAck);
            Register<SArcadeStageReadyAckMessage>(GameRuleOpCode.SArcadeStageReadyAck);
            Register<SArcadeRespawnFailAckMessage>(GameRuleOpCode.SArcadeRespawnFailAck);
            Register<SChangeHPAckMessage>(GameRuleOpCode.SChangeHPAck);
            Register<SChangeMPAckMessage>(GameRuleOpCode.SChangeMPAck);
            Register<SArcadeChangeStageAckMessage>(GameRuleOpCode.SArcadeChangeStageAck);
            Register<SArcadeStageSelectAckMessage>(GameRuleOpCode.SArcadeStageSelectAck);
            Register<SArcadeSaveDataInfAckMessage>(GameRuleOpCode.SArcadeSaveDataInfAck);
            Register<SSlaughterAttackPointAckMessage>(GameRuleOpCode.SSlaughterAttackPointAck);
            Register<SSlaughterHealPointAckMessage>(GameRuleOpCode.SSlaughterHealPointAck);
            Register<SChangeBonusTargetAckMessage>(GameRuleOpCode.SChangeBonusTargetAck);
            Register<SArcadeLoadingSucceedAckMessage>(GameRuleOpCode.SArcadeLoadingSucceedAck);
            Register<SArcadeAllLoadingSucceedAckMessage>(GameRuleOpCode.SArcadeAllLoadingSucceedAck);
            Register<SUseCoinAckMessage>(GameRuleOpCode.SUseCoinAck);
            Register<SLuckyShotAckMessage>(GameRuleOpCode.SLuckyShotAck);
            Register<SGameRuleChangeTheFirstAckMessage>(GameRuleOpCode.SGameRuleChangeTheFirstAck);
            Register<SDevLogStartAckMessage>(GameRuleOpCode.SDevLogStartAck);
            Register<SCompulsionLeaveRequestAckMessage>(GameRuleOpCode.SCompulsionLeaveRequestAck);
            Register<SCompulsionLeaveResultAckMessage>(GameRuleOpCode.SCompulsionLeaveResultAck);
            Register<SCompulsionLeaveActionAckMessage>(GameRuleOpCode.SCompulsionLeaveActionAck);
            Register<SCaptainLifeRoundSetUpAckMessage>(GameRuleOpCode.SCaptainLifeRoundSetUpAck);
            Register<SCaptainSubRoundEndReasonAckMessage>(GameRuleOpCode.SCaptainSubRoundEndReasonAck);
            Register<SCurrentRoundInformationAckMessage>(GameRuleOpCode.SCurrentRoundInformationAck);

            // C2S
            Register<CEnterPlayerReqMessage>(GameRuleOpCode.CEnterPlayerReq);
            Register<CLeavePlayerRequestReqMessage>(GameRuleOpCode.CLeavePlayerRequestReq);
            Register<CChangeTeamReqMessage>(GameRuleOpCode.CChangeTeamReq);
            Register<CAutoAssingTeamReqMessage>(GameRuleOpCode.CAutoAssingTeamReq);
            Register<CAutoMixingTeamReqMessage>(GameRuleOpCode.CAutoMixingTeamReq);
            Register<CMixChangeTeamReqMessage>(GameRuleOpCode.CMixChangeTeamReq);
            Register<CEventMessageReqMessage>(GameRuleOpCode.CEventMessageReq);
            Register<CReadyRoundReqMessage>(GameRuleOpCode.CReadyRoundReq);
            Register<CBeginRoundReqMessage>(GameRuleOpCode.CBeginRoundReq);
            Register<CAvatarDurabilityDecreaseReqMessage>(GameRuleOpCode.CAvatarDurabilityDecreaseReq);
            Register<CAvatarChangeReqMessage>(GameRuleOpCode.CAvatarChangeReq);
            Register<CChangeRuleNotifyReqMessage>(GameRuleOpCode.CChangeRuleNotifyReq);
            Register<CMissionScoreReqMessage>(GameRuleOpCode.CMissionScoreReq);
            Register<CScoreKillReqMessage>(GameRuleOpCode.CScoreKillReq);
            Register<CScoreKillAssistReqMessage>(GameRuleOpCode.CScoreKillAssistReq);
            Register<CScoreOffenseReqMessage>(GameRuleOpCode.CScoreOffenseReq);
            Register<CScoreOffenseAssistReqMessage>(GameRuleOpCode.CScoreOffenseAssistReq);
            Register<CScoreDefenseReqMessage>(GameRuleOpCode.CScoreDefenseReq);
            Register<CScoreDefenseAssistReqMessage>(GameRuleOpCode.CScoreDefenseAssistReq);
            Register<CScoreHealAssistReqMessage>(GameRuleOpCode.CScoreHealAssistReq);
            Register<CScoreGoalReqMessage>(GameRuleOpCode.CScoreGoalReq);
            Register<CScoreReboundReqMessage>(GameRuleOpCode.CScoreReboundReq);
            Register<CScoreSuicideReqMessage>(GameRuleOpCode.CScoreSuicideReq);
            Register<CScoreTeamKillReqMessage>(GameRuleOpCode.CScoreTeamKillReq);
            Register<CItemsChangeReqMessage>(GameRuleOpCode.CItemsChangeReq);
            Register<CPlayerGameModeChangeReqMessage>(GameRuleOpCode.CPlayerGameModeChangeReq);
            Register<CArcadeAttackPointReqMessage>(GameRuleOpCode.CArcadeAttackPointReq);
            Register<CArcadeScoreSyncReqMessage>(GameRuleOpCode.CArcadeScoreSyncReq);
            Register<CArcadeBeginRoundReqMessage>(GameRuleOpCode.CArcadeBeginRoundReq);
            Register<CArcadeStageClearReqMessage>(GameRuleOpCode.CArcadeStageClearReq);
            Register<CArcadeStageFailedReqMessage>(GameRuleOpCode.CArcadeStageFailedReq);
            Register<CArcadeStageInfoReqMessage>(GameRuleOpCode.CArcadeStageInfoReq);
            Register<CArcadeEnablePlayTimeReqMessage>(GameRuleOpCode.CArcadeEnablePlayTimeReq);
            Register<CArcadeRespawnReqMessage>(GameRuleOpCode.CArcadeRespawnReq);
            Register<CArcadeStageReadyReqMessage>(GameRuleOpCode.CArcadeStageReadyReq);
            Register<CArcadeStageSelectReqMessage>(GameRuleOpCode.CArcadeStageSelectReq);
            Register<CSlaughterAttackPointReqMessage>(GameRuleOpCode.CSlaughterAttackPointReq);
            Register<CSlaughterHealPointReqMessage>(GameRuleOpCode.CSlaughterHealPointReq);
            Register<CArcadeLoadingSucceesReqMessage>(GameRuleOpCode.CArcadeLoadingSucceesReq);
            Register<CUseCoinReqMessage>(GameRuleOpCode.CUseCoinReq);
            Register<CBeginResponeReqMessage>(GameRuleOpCode.CBeginResponeReq);
            Register<CWeaponFireReqMessage>(GameRuleOpCode.CWeaponFireReq);
            Register<CCompulsionLeaveRequestReqMessage>(GameRuleOpCode.CCompulsionLeaveRequestReq);
            Register<CCompulsionLeaveVoteReqMessage>(GameRuleOpCode.CCompulsionLeaveVoteReq);
        }
    }
}
